// Writes src/design/tokens.css from src/design/tokens.ts, so the stylesheets
// and the TypeScript spell the same values.
//
// tokens.ts stays the source: it is where the tokens are documented, and code
// that needs a real value rather than a CSS reference — the map's markers,
// which are built as an SVG string — still gets one. This script only makes
// the same table reachable from CSS, as `var(--fh-accent)` and friends.
//
// Re-run with `npm run build:tokens` after changing tokens.ts.

import { writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { color, device, font, layout } from '../src/design/tokens.ts'

/** `surfaceAlt` → `--fh-surface-alt`. */
const name = (group, key) => `--fh-${group}${kebab(key)}`
const kebab = (k) => k.replace(/[A-Z]/g, (c) => '-' + c.toLowerCase())

const section = (title, group, table, unit = '') =>
  `  /* ${title} */\n` +
  Object.entries(table)
    .map(([k, v]) => `  ${name(group, k)}: ${v}${unit};`)
    .join('\n')

const css = `/* Generated by scripts/build-tokens.mjs — edit src/design/tokens.ts instead. */

:root {
${section('Colour', '', color)}

${section('Type', 'font-', font)}

${section('The device frame the design was drawn against', 'device-', device, 'px')}

${section('Where things sit inside it', '', layout, 'px')}
}
`

const out = fileURLToPath(new URL('../src/design/tokens.css', import.meta.url))
await writeFile(out, css)
console.log(`tokens.css written — ${Object.keys(color).length} colours, ${Object.keys(font).length} faces`)
