// Fetches the design's three Google fonts and writes src/assets/fonts.css with
// every face inlined as a data: URI.
//
// Inlining rather than <link>ing them serves two goals: the app has no runtime
// dependency on fonts.gstatic.com, and the single-file preview build stays
// self-contained (its host blocks external requests, so a <link> would silently
// fall back to system fonts and lose the design's character).
//
// Only the `latin` subset is kept — Spanish accents live in U+0000-00FF.
// Re-run with `npm run build:fonts` if the font list in the design changes.

import { writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Archivo:wght@500;600;700;800' +
  '&family=IBM+Plex+Mono:wght@400;500;600&family=Instrument+Serif:ital@0;1&display=swap'

// woff2 is only served to browser-like clients; Node's default UA gets ttf.
const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36'

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text()

// Each @font-face is preceded by a `/* subset */` comment naming its subset.
const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)]
const latin = blocks.filter(([, subset]) => subset === 'latin').map(([, , block]) => block)
if (!latin.length) throw new Error('no latin @font-face blocks found — did the CSS format change?')

let total = 0
const out = await Promise.all(
  latin.map(async (block) => {
    const url = block.match(/url\((https:\/\/[^)]+)\)/)?.[1]
    if (!url) throw new Error(`@font-face without a url(): ${block}`)
    const bytes = Buffer.from(await (await fetch(url)).arrayBuffer())
    total += bytes.length
    return block
      .replace(/url\(https:\/\/[^)]+\)/, `url(data:font/woff2;base64,${bytes.toString('base64')})`)
      .replace(/\n\s*unicode-range:[^;]*;/, '') // single subset, so the range is noise
  })
)

const header =
  '/* GENERATED by scripts/build-fonts.mjs — do not edit. Run `npm run build:fonts`. */\n'
const target = fileURLToPath(new URL('../src/assets/fonts.css', import.meta.url))
await writeFile(target, header + out.join('\n') + '\n')

console.log(`fonts.css written — ${latin.length} faces, ${(total / 1024).toFixed(0)} kB of woff2`)
